//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int IncomeId { get; set; }
        public int IncomeTypeId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime IncomeDate { get; set; }
        public string IncomeMonth { get; set; }
        public string rowguid { get; set; }
    
        public virtual IncomeType IncomeType { get; set; }
    }
}
