//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outgoings
    {
        public int OutgoingId { get; set; }
        public string Description { get; set; }
        public Nullable<int> OutgoingType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime OutgoingDate { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual OutgoingType OutgoingType1 { get; set; }
    }
}
